In [26]:
%pip install seaborn

import numpy as np
from typing import Tuple
from scipy.stats import mode
from sklearn.metrics import confusion_matrix
import seaborn as sns

csv_path = "iris.csv"

     ---------------------------------------- 0.0/293.3 kB ? eta -:--:--
     -------------------------------------- 293.3/293.3 kB 9.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [9]:
def load_csv(csv_path:str) -> Tuple[np.ndarray, np.ndarray]:
    np.random.seed(42)
    dataset = np.genfromtxt(csv_path,delimiter=',')
    np.random.shuffle(dataset)
    x,y = dataset[:,:-1],dataset[:,-1]
    return x,y

In [10]:
x,y = load_csv(csv_path)
x.shape,y.shape

((150, 4), (150,))

In [11]:
np.mean(x,axis=0),np.var(x,axis=0)

(array([nan, nan, nan, nan]), array([nan, nan, nan, nan]))

In [12]:
np.nanmean(x,axis=0),np.nanvar(x,axis=0)

(array([ 355.46503497, -280.09189189,    2.95      ,   21.74726027]),
 array([1.73561968e+07, 1.18405444e+07, 1.51049922e+04, 6.11729208e+04]))

In [15]:
x[np.isnan(x)] = 3.5

In [24]:
np.where(x < 0.0)

(array([], dtype=int64), array([], dtype=int64))

In [23]:
y = np.delete(y,np.where(x < 0.0)[0], axis=0)
y = np.delete(y,np.where(x > 10.0)[0], axis=0)

x = np.delete(x,np.where(x < 0.0)[0], axis=0)
x = np.delete(x,np.where(x > 10.0)[0], axis=0)
x.shape,y.shape

((144, 4), (144,))

In [21]:
def train_test_split(features:np.ndarray,labels:np.ndarray,test_split_ratio:float)-> Tuple[np.ndarray,np.ndarray,np.ndarray,np.ndarray]:
    test_size = int(len(features) * test_split_ratio)
    train_size = len(features) - test_size
    assert len(features)  == test_size + train_size, "Size mismatch!"

    x_train,y_train = features[:train_size,:], labels[:train_size]
    x_test,y_test = features[train_size:,:], labels[train_size:]
    return x_train,y_train,x_test,y_test

In [22]:
x_train,y_train,x_test,y_test = train_test_split(x,y,0.2)

In [18]:
def euclidean(points:np.ndarray,element_of_x:np.ndarray)->np.ndarray:
    return np.sqrt(np.sum((points - element_of_x)**2, axis=1))

In [16]:
def predict(x_train:np.ndarray,y_train:np.ndarray,x_test:np.ndarray,k:int) -> np.ndarray:
    label_pred =[]
    for x_test_element in x_test:
        distances = euclidean(x_train,x_test)
        distances = np.array(sorted(zip(distances,y_train)))
        label_pred = mode(distances[:k,1],keepdims=False).mode
        label_pred .append(labels_pred)
    return np.array(label_pred,dtype=np.int64)

In [17]:
def accuracy(y_test:np.ndarray,y_preds:np.ndarray)->float:
    true_positve = (y_test == y_preds).sump()
    return true_positve/ len(y_test) *100

In [27]:
def plot_confurion_matrix(y_test:np.ndarray,y_preds:np.ndarray):
    conf_matrix = confusion_matrix(y_test,y_preds)
    sns.heatmap(conf_matrix,annot=True)
    